### ISSUE TITLE
Dúvida sobre licença e possibilidade de uso da arte em camiseta

### ISSUE THREAD

**Issue by teles** [QuebraDev/pessoas-programadoras-antifascistas#1]
Bom dia, tudo bem?

Eu vi um adesivo com a estampa no centro de SP, me interessei e achei esse repositório.
Pensei em sugerir para a https://www.elcabriton.com/ produzir camiseta com essa estampa, mas isso esbarra em questões de licença. 

Então queria saber se essa estampa tem um licenciamento que permita sua reprodução em uma camiseta pela El Cabriton, por exemplo. 

PS: não represento El Cabriton, só estou querendo a camiseta com uma boa qualidade haha

Abraço

**Comment by eptaccio** [comment]
opa, pode usar suave!

**Comment by reginaldojuniorcreditas** [comment]
Salve mano @teles que daora que viu um adesivo rodando por ai. Mano nossas artes são tudo construida em creative commons e código em MIT. Ou seja, tudo é aberto para qualquer um utilizar, adaptar e redistribuir. Pode da-lhe, e depois que a camiseta ficar pronta manda foto pra nois ou nos marca nas redes sociais @quebradev 

Abs

**Comment by reginaldojunior** [comment]
Salve mano @teles que daora que viu um adesivo rodando por ai. Mano nossas artes são tudo construida em creative commons e código em MIT. Ou seja, tudo é aberto para qualquer um utilizar, adaptar e redistribuir. Pode da-lhe, e depois que a camiseta ficar pronta manda foto pra nois ou nos marca nas redes sociais https://github.com/QuebraDev

Abs

**Comment by teles** [comment]
Valeu, @reginaldojunior!

Vou ver com o pessoal da El Cabriton!
Olha só o adesivo que vi pela Rua Consolação, não é igual mas bem parecido

![WhatsApp Image 2023-01-18 at 09 17 04 (1)](https://user-images.githubusercontent.com/762639/213532137-55de7909-53b7-4741-9b97-bb713f826295.jpeg)

Abraço

**Comment by reginaldojuniorcreditas** [comment]
@teles muito foda, conheço o mano que mandou imprimir esses ai
